# -*- coding: utf-8 -*-
"""DataPreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lju24LftYnTMu8eJ-SDcnptASXBaNEim
"""

import pandas as pd
import numpy as np

data = pd.read_csv('googleplaystore.csv')
data.head(5)

#Average of Rating
data_filtered = data.dropna(subset=['Rating'])
avgg = int(sum(data_filtered['Rating'])/len(data_filtered['Rating']))
print(avgg)

#List of Rating above 4
data_filtered = data[data['Rating'] > 4]
display(data_filtered)

#Unique Category in Data
data_filtered = data['Category'].unique()
for i in range(len(data_filtered)):
    print(data_filtered[i])

#List of Unique Categories with number
for name in data['Category'].unique():
  ct = 0
  for i in data['Category']:
    if name == i:
      ct += 1
  print(name, ct)



df = pd.read_csv('Data.csv')
df.head()